# RBAC Configuration for K8S Daily Summary CLI
# Apply this configuration to grant necessary permissions

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-summary-reader
  labels:
    app: k8s-summary
rules:
# Core resources
- apiGroups: [""]
  resources: ["pods", "events", "namespaces"]
  verbs: ["get", "list"]
  
# Batch resources (Jobs and CronJobs)
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list"]
  
# Apps resources (Deployments, ReplicaSets)
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list"]

---
# Example ClusterRoleBinding for a service account
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-summary-binding
  labels:
    app: k8s-summary
subjects:
- kind: ServiceAccount
  name: k8s-summary
  namespace: default
roleRef:
  kind: ClusterRole
  name: k8s-summary-reader
  apiGroup: rbac.authorization.k8s.io

---
# Example ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-summary
  namespace: default
  labels:
    app: k8s-summary